### ISSUE TITLE
Overwriting certain objects while parsing maps

### ISSUE THREAD

**Issue by myuce** [Perryvw/PHPValveKV#1]
I've been working on a map converter and I realized that the parser redefines objects like entities while parsing VMF files. If you try parsing a map file, you'll see that only the last entity in the vmf file is in the array.

**Comment by Perryvw** [comment]
Can you paste the KV you are trying to parse somewhere and drop a link here?

**Comment by myuce** [comment]
http://www.mediafire.com/file/xyeg64y6m8q01sn/Valve_maps.zip

You can try one of the files from this archive. It parses and doesn't overwrite other objects that has the same name (such as solid, side, camera etc.) but for some reason it overwrites entities, leaving the last entity in the vmf file as the only element of that array.

**Comment by Perryvw** [comment]
Should be fixed with 47d19d9ae2acee93705e52f29d7e3576eca37279, try it out!
